services:
  - type: web
    name: ll-trivia-v2
    runtime: python
    buildCommand: cd ll-trivia-v2/frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: cd ll-trivia-v2/backend && gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
